version: '3.8'

services:
  php:
    image: pandu321/yii2-app:latest
    expose:
      - 9000
    networks:
      - yii2net

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - yii2net

networks:
  yii2net:
