version: '3.7'

services:
  yii2app:
    build: .
    image: pandu321/yii2-app:latest
    ports:
      - "8080:80"  # Exposing port 8080 on the host to access the container
    networks:
      - yii2app_net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  yii2app_net:
    driver: overlay
