version: '3.8'

services:
  yii2-app:
    image: pandu321/yii2-app:latest
    build:
      context: ./src
      dockerfile: Dockerfile  # Build from Dockerfile inside src/
    volumes:
      - yii2-app-data:/var/www/html  # Persistent storage for application
    networks:
      - yii2-net

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d  # Mount the NGINX config folder (local)
      - ./src:/var/www/html  # Mount the source code into NGINX
    ports:
      - "80:80"  # Expose NGINX to the host's port 80
    depends_on:
      - yii2-app  # Ensure Yii2 app starts first
    networks:
      - yii2-net

volumes:
  yii2-app-data:
    driver: local  # Volume for persistent data

networks:
  yii2-net:
    driver: bridge  # Create a bridge network for communication

